# Generated by Django 5.1.5 on 2025-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('soil_type', models.CharField(max_length=255)),
                ('pH_range', models.CharField(max_length=50)),
                ('planting_depth', models.CharField(blank=True, max_length=50, null=True)),
                ('spacing', models.CharField(blank=True, max_length=100, null=True)),
                ('growing_period', models.CharField(blank=True, max_length=50, null=True)),
                ('water_requirements', models.TextField()),
                ('fertilization', models.TextField()),
                ('common_diseases', models.TextField()),
                ('common_pests', models.TextField()),
                ('harvesting_details', models.TextField()),
            ],
        ),
    ]
