# Generated by Django 5.1.5 on 2025-01-31 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='common_diseases',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='common_pests',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fertilization',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='harvesting_details',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='planting_depth',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='spacing',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='water_requirements',
        ),
        migrations.AlterField(
            model_name='crop',
            name='growing_period',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('remedies', models.JSONField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('details', models.JSONField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.crop')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
    ]
